### ISSUE TITLE
Add OEM Config

### ISSUE THREAD

**Issue by SlaterByte** [freegeekchicago/fgc-installscript#22]
Add oem-config and oem-config-kde packages for helping us reset the OS to "first-start" state for customers. This needs to be done in conjunction with changing preseed user and password to oem,oem.

**Comment by steenburgh** [comment]
@ahanson Can we close all these kubuntu issues? I don't forsee us touching kubuntu 14.04 any time in the near future.

**Comment by ahanson** [comment]
We haven't used Kubuntu for a while now.
