### ISSUE TITLE
Add inxi to installscript

### ISSUE THREAD

**Issue by ahanson** [freegeekchicago/fgc-installscript#33]
[Inxi](http://www.binarytides.com/inxi-system-information-linux/) is a slightly more concise hardware information script than [lshw](http://www.ezix.org/project/wiki/HardwareLiSter).

**Comment by bmintz** [comment]
agreed.
`inxi -v 3` is all we need imho and it doesn't require root.

but we'd have to update *all* of the documentation and educate everyone on using inxi instead of lshw. so this may be a little harder than a few commits.

**Comment by ahanson** [comment]
I've added inxi. We'll add it to the build sheet soon.
