### ISSUE TITLE
Add to install.sh if possible

### ISSUE THREAD

**Issue by DanFGC** [freegeekchicago/fgc-installscript#36]
1. add following command to fix some issues with Brasero:
   sudo apt-get install cdrdao
2. Autodetect if there is a webcam installed; if so, then
   sudo apt-get install cheese

**Comment by steenburgh** [comment]
I don't see brasero being installed w/ mint + it looks like cheese is already being auto installed here:

**Comment by ahanson** [comment]
I think we've got the webcam detection working.

**Comment by ahanson** [comment]
I added cdrdao, for what it's worth.
