### ISSUE TITLE
Flash plugin

### ISSUE THREAD

**Issue by DanFGC** [freegeekchicago/fgc-installscript#43]
Flash doesn't work in Chromium even after installing pepperflashplugin-nonfree. It is depricated, replaced by adobe-flashplugin.  Needs to have Canonical Partners allowed in Software & Updates
See https://wiki.ubuntu.com/Chromium/Getting-Flash

**Comment by ahanson** [comment]
I made a pull request that might fix this. Can we try testing this out during build?

**Comment by steenburgh** [comment]
Of note: When you put 'fixes #issuenumber' in a commit, the associated issue will automatically be closed when you merge the pull request the commit is in. https://help.github.com/articles/closing-issues-using-keywords/
