### ISSUE TITLE
Spanish packages

### ISSUE THREAD

**Issue by ahanson** [freegeekchicago/fgc-installscript#56]
Do we need to install Spanish language packages if we're using the OEM script (which allows people to choose their language after purchasing a machine)?

**Comment by southpauw** [comment]
I think we should probably add it in given the demographics of the city. Since we're updating the script in general this would be a good time to do it,

**Comment by steenburgh** [comment]
I think we might already be doing this, but I'm unfamiliar with linux/ubuntu language packs. https://github.com/freegeekchicago/fgc-installscript/blob/master/install.sh#L242

**Comment by ahanson** [comment]
Ok, let's keep it.
