### ISSUE TITLE
Linux Mint 18.3 Xfce Build Checklist

### ISSUE THREAD

**Issue by southpauw** [freegeekchicago/fgc-installscript#57]
Attached is the updated build checklist. I would like to run through it one more time. I added in the VLC commands for a computer with two DVD's. I would like to confirm it will work. @ahanson @steenburgh @SlaterByte @derrg 
[build linux mint_Mar-2018.pdf](https://github.com/freegeekchicago/fgc-installscript/files/1850304/build.linux.mint_Mar-2018.pdf)
-Phillip Kinnison

**Comment by steenburgh** [comment]
I really like the improvements you've made, especially the part about cleaning dust/loading bios defaults. The installation instructions will be valuable as well, at least until we get a preseed configuration + network boot setup for mint so we can let the install run automatically.

**Comment by steenburgh** [comment]
For the upgrade instructions section, we've done some work to update the build script, so the extra commands you've added are no longer necessary. 
 ```
rm install.*
wget www.freegeekchicago.org/files/install.txt
sudo sh ./install.txt
sudo apt-get update
sudo apt-get upgrade
```
See #53 #51 if you're curious about some of the things we did.

**Comment by steenburgh** [comment]
I just noticed that you also had instructions there for a computer with 2 DVD drives. The build script doesn't handle a computer with 2 dvds, but my opinion is that we don't need to worry about that. I'm curious what others think.

**Comment by southpauw** [comment]
OK. Great that we added it to the base script. We can plan to run the updated install.txt file and then double-check that none of the manual steps need to be run. For the 2 DVD I think maybe we include it as a note in the manual steps. I've seen a couple instance so we should at least provide the build person the information on how to resolve it.

**Comment by ahanson** [comment]
The new build checklist is really great. Thanks for putting it together.
I've posted it to the FreeGeek Staff Dropbox so that we can print it our
during build.

**Comment by southpauw** [comment]
@ahanson @steenburgh Hey guys. I ran the new install script. All the upgrades worked correctly so there's no need to include them as manual steps anymore. However, the Audio: vlc cdda://dev/sr0 didn't get set in the Removable Media and Drives. The DVD does appear to work correctly.
          > DVD: vlc dvd://dev/sr0
We should test this on a computer with two drives as well.
If you can look at the script I can test again. For now I'll include these as manual steps to check/update.

**Comment by steenburgh** [comment]
Thanks. What did it show instead? It should show 
`/usr/bin/vlc cdda://%d` for audio, and
`/usr/bin/vlc dvd://%d` for video.

**Comment by steenburgh** [comment]
Also to answer your previous question, the install.txt file doesn't need to be updated. The install.txt file just pulls down the latest install.sh directly from github, then runs it.

**Comment by steenburgh** [comment]
As for the issue with the audio not getting properly set, I'll have to debug that on a freegeek machine because it works fine on my virtual machine.

**Comment by southpauw** [comment]
@steenburgh @ahanson  For the Video section is says vlc /dev/sr0 and for the Audio is says the default rhythmbox. I was thinking we should also enable by default the following:
Cameras
 - Import digital photographs when connected
Printers
 - Automatically run a program when a printer is connected (maybe this one isn't needed, but if it would install and drivers needed I think that would be beneficial.

**Comment by steenburgh** [comment]
As for the other suggestions for the build script, could you open an issue or 2 so we can discuss those on a different thread? I'm busy right now or I'd make the issues myself.

**Comment by steenburgh** [comment]
I just ran through the build guide with a few people today - I got 3 pieces of feedback. If we can correct those I'd say the new guide is ready to go. If we can keep the mint install process consistent, it'll really help things go more smoothly as we upgrade all the machines to mint. 
1. We need to mention that you can leave the "select a name for this batch of machines" box blank during the oem install. 
2. We should move the "Hardware Verification" section to after the "System Build" section to match the order they need to be done in.
3. We need to remove all the commands from the "Software Upgrade Instructions" section
```
rm install.*
wget www.freegeekchicago.org/files/install.txt
sudo sh ./install.txt
sudo apt-get update
sudo apt-get upgrade
```
But we need to keep the steps to setup autoplay until I can fix the build script.

**Comment by southpauw** [comment]
OK. I updated the checklist. Can we you check it over one last time. I left in the  
sudo apt-get install libdvd-pkg steps as well. We could remover it, but based on my reading this helps to ensure all DVD's can play in the drive.
I'm not sure if I'll be at FreeGeek on Friday or not, but will do my best to come in for at least a couple hours in the afternoon.
[build linux mint_Mar-2018_v2.pdf](https://github.com/freegeekchicago/fgc-installscript/files/1892672/build.linux.mint_Mar-2018_v2.pdf)


@ahanson @steenburgh

**Comment by steenburgh** [comment]
I'm sorry, I wasn't very clear about the "Software Upgrade section. We need to to *keep* the following commands, not remove them. 

```
rm install.*
wget www.freegeekchicago.org/files/install.txt
sudo sh ./install.txt
sudo apt-get update
sudo apt-get upgrade
```

For the DVD stuff, I'm pretty confident we can leave it out. We recently added libdvdcss (which I think is the same as libdvd-pkg) to the install script, and I didn't see anybody encounter issues with DVDs on Sunday.

**Comment by southpauw** [comment]
Ok, yeah makes sense. Attached is the updated version. I'll be in on Sunday so I can have Bob print new copies out. 
[build linux mint_Apr-2018.pdf](https://github.com/freegeekchicago/fgc-installscript/files/1911288/build.linux.mint_Apr-2018.pdf) @steenburgh @ahanson

**Comment by southpauw** [comment]
Updated file for review @steenburgh @ahanson 
[build linux mint_Mar-2018_v3.zip](https://github.com/freegeekchicago/fgc-installscript/files/1934985/build.linux.mint_Mar-2018_v3.zip)

**Comment by steenburgh** [comment]
I went through and tried to clean up some of the formatting in the document. Please let me know what you think, or if I should revert any changes I made.

[build linux mint_Mar-2018_v4.pdf](https://github.com/freegeekchicago/fgc-installscript/files/1935093/build.linux.mint_Mar-2018_v4.pdf)
[build linux mint_Mar-2018_v4.zip](https://github.com/freegeekchicago/fgc-installscript/files/1935094/build.linux.mint_Mar-2018_v4.zip)

**Comment by steenburgh** [comment]
If we want to make Dan a part of this discussion, we might want to post this on the google group instead, or at least make him aware of this GitHub thread.

**Comment by steenburgh** [comment]
Also if you haven't already it might be a good idea to look at Portland's QC checklist.
http://wiki.freegeek.org/index.php?title=QC_checklist

**Comment by steenburgh** [comment]
I just finished going through things. I made a google doc so we can comment in real time. The link should give you edit permissions. https://docs.google.com/document/d/14gUbH6q6ovJ8BddTq8VQS5lrkitUZYF59SwV-l7eNRA/edit?usp=sharing

**Comment by steenburgh** [comment]
When it comes to the build script, it's actually been in use at FreeGeek for several weeks now and I don't believe anybody has had problems with it. 

That said, I'll take a look at the additions you've made and we can test them some time in the future. However, I don't play on being back at freegeek until June 24th so it'll have to be Alex or someone else that tests the changes.

**Comment by steenburgh** [comment]
I like the additions Dan suggested, especially the one about stress testing the machine. The cleanup process and checking the case for loose/missing parts is also great because it will make us look more professional and instill confidence, both in our customers, and potential volunteers. Anything else we can add to the QA process to make it more thorough would be much appreciated.

**Comment by steenburgh** [comment]
This thread is no longer used - discussions have been moved to the ["FreeGeek Chicago Internal" google group](https://groups.google.com/forum/#!forum/free-geek-chicago-internal). @ahanson would you mind closing this issue for me? I don't have permission to do so.
