### ISSUE TITLE
Use apt-fast for package installation

### ISSUE THREAD

**Issue by steenburgh** [freegeekchicago/fgc-installscript#66]
I haven't tested it myself, but it sounds like [apt-fast](https://github.com/ilikenwf/apt-fast/) could greatly reduce install times. What do you think? [Is our network fast enough to benefit from it?](https://askubuntu.com/questions/52243/what-is-apt-fast-and-should-i-use-it)

**Comment by bmintz** [comment]
I think there's a high chance this would just saturate our DSL line. The intention of the local package mirror (I don't know if it's still up, or up to date) is to speed that process up.

**Comment by steenburgh** [comment]
After watching the install script run through, it looks like the bulk of the time spent by the install script is installing packages, not downloading them, so I don't think apt-fast is going to make a huge difference for us, especially on slower machines which will take longer to run the installations.

@ahanson Please close this issue as it's not worth looking into further.

**Comment by steenburgh** [comment]
I'm closing this issue as it's not worth looking into further.
